# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node-discovery.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node-discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14node-discovery.proto\x12\rnodeDiscovery\"W\n\x13RegisterNodeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\x02\x12\x10\n\x08\x63pu_arch\x18\x03 \x01(\t\x12\x0e\n\x06memory\x18\x04 \x01(\x02\"\'\n\x14RegisterNodeResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"\x11\n\x0fGetNodesRequest\"6\n\x10GetNodesResponse\x12\"\n\x05nodes\x18\x01 \x03(\x0b\x32\x13.nodeDiscovery.Node\"h\n\x04Node\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\x02\x12\x10\n\x08\x63pu_arch\x18\x04 \x01(\t\x12\x0e\n\x06memory\x18\x05 \x01(\x02\x12\r\n\x05state\x18\x06 \x01(\t2g\n\x0cNodeRegister\x12W\n\x0cRegisterNode\x12\".nodeDiscovery.RegisterNodeRequest\x1a#.nodeDiscovery.RegisterNodeResponse2W\n\x08GetNodes\x12K\n\x08GetNodes\x12\x1e.nodeDiscovery.GetNodesRequest\x1a\x1f.nodeDiscovery.GetNodesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERNODEREQUEST']._serialized_start=39
  _globals['_REGISTERNODEREQUEST']._serialized_end=126
  _globals['_REGISTERNODERESPONSE']._serialized_start=128
  _globals['_REGISTERNODERESPONSE']._serialized_end=167
  _globals['_GETNODESREQUEST']._serialized_start=169
  _globals['_GETNODESREQUEST']._serialized_end=186
  _globals['_GETNODESRESPONSE']._serialized_start=188
  _globals['_GETNODESRESPONSE']._serialized_end=242
  _globals['_NODE']._serialized_start=244
  _globals['_NODE']._serialized_end=348
  _globals['_NODEREGISTER']._serialized_start=350
  _globals['_NODEREGISTER']._serialized_end=453
  _globals['_GETNODES']._serialized_start=455
  _globals['_GETNODES']._serialized_end=542
# @@protoc_insertion_point(module_scope)
