apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: flask-api-rolebinding
subjects:
- kind: ServiceAccount
  name: flask-api-sa
  namespace: default
roleRef:
  kind: Role
  name: flask-api-role
  apiGroup: rbac.authorization.k8s.io
