statefulset:
  replicas: 3

insecure: true

# Minimal storage size for local development
storage:
  persistentVolume:
    enabled: false

# Expose services for local access
service:
  public:
    type: NodePort  # Allows external access via a port
    ports:
      http: 8080  # Admin UI port
      sql: 26257  # SQL port
  internal:
    type: ClusterIP  # Internal-only service for cluster communication

# Disable TLS for local development (unsafe for production)
tls:
  enabled: false
  service:
    enabled: false

# Disable Admin UI authentication for local testing
adminui:
  service:
    type: NodePort
  authentication: false
