# Single-node deployment for local MacBook (No High Availability)
statefulset:
  replicas: 1
  resources:
    requests:
      cpu: "100m"       # Reduce CPU request
      memory: "256Mi"   # Reduce memory request
    limits:
      cpu: "250m"       # Reduce CPU limit
      memory: "512Mi"   # Reduce memory limit

# Minimal storage size for local development
storage:
  persistentVolume:
    enabled: true
    size: 1Gi  # Reduce storage to 1Gi (less disk usage)
    storageClass: "standard"

# Change service type for easier local access
service:
  public:
    type: NodePort  # Allows access via a local port
  internal:
    type: ClusterIP

# Reduce memory allocation for SQL execution & caching
conf:
  cache: "128Mi"           # Reduce cache size to save memory
  max-sql-memory: "128Mi"  # Reduce SQL memory usage

# Disable TLS for local development (unsafe for production)
tls:
  enabled: false

# Disable Admin UI authentication for local testing
adminui:
  authentication: false
