# Single-node deployment for local MacBook
statefulset:
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Reduced storage size for local testing
storage:
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: "standard"

# Change service type for easier local access
service:
  public:
    type: NodePort  # Allows access via a local port
  internal:
    type: ClusterIP

# Memory settings (1/4th of allocated memory)
conf:
  cache: "256Mi"           # 1/4 of 1Gi
  max-sql-memory: "256Mi"  # 1/4 of 1Gi

# Disable TLS for local development
tls:
  enabled: false

# Disable Admin UI authentication for local testing
adminui:
  authentication: false
