apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: function-deployment-rolebinding
  namespace: default  # Match the namespace
subjects:
  - kind: ServiceAccount
    name: function-deployment-sa
    namespace: default
roleRef:
  kind: Role
  name: function-deployment-role
  apiGroup: rbac.authorization.k8s.io
