apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: function-preparation-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: function-preparation  # Must match the label in your Service
  endpoints:
    - port: http  # Must match the port name in your Service
      path: /metrics
      interval: 15s  # Scrape metrics every 15 seconds