apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  DATABASE_URL: "postgresql://your_user:your_password@cockroachdb-service:26257/your_database"
  KAFKA_BROKER: "kafka-service:9092"
