# Disable components not needed for local development
alertmanager:
  enabled: false

# Enable Grafana with minimal resources
grafana:
  enabled: true
  persistence:
    enabled: false  # Disable persistence to save disk space
  adminPassword: "admin"  # Default login (change for security)
  service:
    type: NodePort  # Expose Grafana externally
  sidecar:
    datasources:
      enabled: true  # Automatically detects Prometheus as a datasource

# Minimize Prometheus resource usage
prometheus:
  service:
    type: NodePort
  enabled: true
  prometheusSpec:
    retention: "30m"  # Retain data for 30 minutes
  persistence:
    enabled: false  # Disable persistence to save disk space

# Disable nodeExporter (it's separate from Prometheus)
nodeExporter:
  enabled: false

