replicaCount: 1

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

persistence:
  size: 5Gi

service:
  type: ClusterIP

auth:
  clientProtocol: plaintext

kraft:
  enabled: true

zookeeper:
  enabled: false
