replicaCount: 1

resources:
  requests:
    memory: 256Mi   # Lower memory usage
    cpu: 100m       # Minimal CPU usage
  limits:
    memory: 512Mi   # Prevent excessive memory usage
    cpu: 250m       # Cap CPU consumption

persistence:
  size: 1Gi        # Minimal disk usage for local testing

service:
  type: ClusterIP  # No need for external access

auth:
  clientProtocol: plaintext  # No security needed for local testing

kraft:
  enabled: true
  clusterId: "test-cluster"  # Simple fixed cluster ID for local use

zookeeper:
  enabled: false  # Disable ZooKeeper since KRaft mode is enabled
