replicaCount: 3

persistence:
  enabled: false
  dataLogDir:
    enabled: false
  dataDir:
    enabled: false

volumes:
  logs:
    emptyDir: {}
  data:
    emptyDir: {}

service:
  type: ClusterIP
  headless:
    enabled: true
    broker:
      annotations: { }
      labels: { }
    controller:
      annotations: { }
      labels: { }

auth:
  enabled: false
  clientProtocol: plaintext

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

kraft:
  enabled: true
  clusterId: "dev-kafka-cluster"
  metadataQuorum: 3

zookeeper:
  enabled: false

provisioning:
  enabled: true
  topics:
    - name: function-preparation
      partitions: 3
      replicationFactor: 3
    - name: function-deployment
      partitions: 3
      replicationFactor: 3
    - name: function-execution
      partitions: 3
      replicationFactor: 3
    - name: changefeed-functions
      partitions: 3
      replicationFactor: 3

volumePermissions:
  enabled: false

controller:
  persistence:
    enabled: false
  logPersistence:
    enabled: false
  volumes:
    data:
      emptyDir: {}
    logs:
      emptyDir: {}

broker:
  persistence:
    enabled: false
  logPersistence:
    enabled: false
  volumes:
    data:
      emptyDir: {}
    logs:
      emptyDir: {}