loki:
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    fsGroupChangePolicy: "Always"
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true

minio:
  enabled: true
  persistence:
    enabled: false  # Disable default PVC creation
  extraVolumes:
    - name: minio-storage
      hostPath:
        path: /mnt/data/minio  # Change to a directory on your node
        type: DirectoryOrCreate

  extraVolumeMounts:
    - name: minio-storage
      mountPath: /data

  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    fsGroupChangePolicy: "Always"

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: false  # Disable default PVC creation
  extraVolumes:
    - name: loki-storage
      hostPath:
        path: /mnt/data/loki  # Directory on the host node
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki  # Mount path within the container
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    fsGroupChangePolicy: "Always"

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0