# Minimal resource allocation for development
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

# Promtail configuration for Kubernetes pod scraping
config:
  logLevel: info
  clients:
    - url: http://loki-gateway.default.svc.cluster.local/loki/api/v1/push  # Adjust Loki URL as necessary
  positions:
    filename: /run/promtail/positions.yaml
  scrape_configs:
    - job_name: "kubernetes-pods"
      pipeline_stages:
        - cri: {}  # Auto-detect and parse container runtime logs
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: replace
          target_label: app
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
        - source_labels: [__meta_kubernetes_container_name]
          action: replace
          target_label: container
        - source_labels: [__meta_kubernetes_node_name]
          action: replace
          target_label: node
