config:
  clients:
    - url: http://loki:3100/loki/api/v1/push  # Sends logs to Loki

  snippets:
    pipelineStages:
      - docker: {}  # Extract logs from Docker containers (for local Kubernetes)

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

service:
  type: ClusterIP  # Internal service

persistence:
  enabled: false  # No disk storage needed
